// 列出所有的 动作名称
export const REQUEST_QUESTION_LIST = 'REQUEST_QUESTION_LIST'

export const CREATE_NEW_NAIRE = 'CREATE_NEW_NAIRE'
export const SAVE_NEW_NAIRE = 'SAVE_NEW_NAIRE'
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION'
export const DEL_QUESTION = 'DEL_QUESTION'
export const DEL_OPTION = 'DEL_OPTION'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const UPDATE_INTRO = 'UPDATE_INTRO'
export const UPDATE_DEADLINE = 'UPDATE_DEADLINE'
